# Generated by Django 6.0 on 2025-12-25 20:03

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=300)),
                ('span', django.contrib.postgres.fields.ranges.IntegerRangeField()),
                ('Mat', models.IntegerField(blank=True, null=True)),
                ('Inns', models.IntegerField(blank=True, null=True)),
                ('Runs', models.IntegerField(blank=True, null=True)),
                ('HS', models.CharField(blank=True, max_length=4, null=True)),
                ('Ave', models.FloatField(blank=True, null=True)),
                ('BF', models.IntegerField(blank=True, null=True)),
                ('SR', models.FloatField(blank=True, null=True)),
                ('Cent', models.IntegerField(blank=True, null=True)),
                ('half_Cent', models.IntegerField(blank=True, null=True)),
                ('duck', models.IntegerField(blank=True, null=True)),
                ('fours', models.IntegerField(blank=True, null=True)),
                ('sixes', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bowling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=300)),
                ('span', django.contrib.postgres.fields.ranges.IntegerRangeField()),
                ('Mat', models.IntegerField(blank=True, null=True)),
                ('Inns', models.IntegerField(blank=True, null=True)),
                ('Overs', models.FloatField(blank=True, null=True)),
                ('Mdns', models.IntegerField(blank=True, null=True)),
                ('Runs', models.IntegerField(blank=True, null=True)),
                ('Wkts', models.IntegerField(blank=True, null=True)),
                ('BBI', models.CharField(blank=True, max_length=10, null=True)),
                ('Ave', models.FloatField(blank=True, null=True)),
                ('Econ', models.FloatField(blank=True, null=True)),
                ('SR', models.FloatField(blank=True, null=True)),
                ('fours', models.IntegerField(blank=True, null=True)),
                ('fives', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fielding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=300)),
                ('span', django.contrib.postgres.fields.ranges.IntegerRangeField()),
                ('Mat', models.IntegerField(blank=True, null=True)),
                ('Inns', models.IntegerField(blank=True, null=True)),
                ('Dis', models.IntegerField(blank=True, null=True)),
                ('Ct', models.IntegerField(blank=True, null=True)),
                ('St', models.IntegerField(blank=True, null=True)),
                ('Ct_Wk', models.IntegerField(blank=True, null=True)),
                ('Ct_Fi', models.IntegerField(blank=True, null=True)),
                ('MD_total', models.IntegerField(blank=True, null=True)),
                ('MD_Ct', models.IntegerField(blank=True, null=True)),
                ('MD_St', models.IntegerField(blank=True, null=True)),
                ('DPI', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=300)),
            ],
        ),
    ]
