# Generated by Django 6.0 on 2025-12-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Players',
        ),
    ]
