import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .services.ai_query import execute_SQL, fallback_to_LLM, build_sql
from .services.redis_check import get_cache, set_cache, redis_available
from .services.metric_normalization import extract_metric
from .services.extract_names import extract_player_name
from django.shortcuts import render
from psycopg2.extras import NumericRange
import re

INVALID_SQL = {
    "not in the data",
    "please ask cricket related questions",
    None,
    ""
}

def landing(request):
    return render(request, "core/landing.html")

def home(request):
    return render(request, "core/index.html")

def span_to_JSON(columns, row):
    obj = {}
    for cols, value in zip(columns, row):
        if isinstance(value, NumericRange):
            obj[cols] = {
                "start": value.lower,
                "end": value.upper,
                "start_inclusive": value.lower_inc,
                "end_inclusive": value.upper_inc
            }
        else:
            obj[cols] = value
    return obj

@csrf_exempt
def api_query(request):
    if request.method != "POST":
        return JsonResponse({"error": "POST only"}, status=405)

    try:
        body = json.loads(request.body)
    except json.JSONDecodeError:
        return JsonResponse({"error": "Invalid JSON"}, status=400)

    question = body.get("question")
    print(question)
    use_fallback = body.get("use_fallback", False)

    if not question:
        return JsonResponse({"error": "No question provided"}, status=400)

    # Normalize question
    normalized_question = " ".join(re.sub(r"[^a-z0-9\s]", " ", question.lower()).split())

    # Feature extraction
    table, metric, remaining = extract_metric(normalized_question)
    player_name = extract_player_name(remaining)
    print(f"remaining='{remaining}', player={player_name}")
    has_player = player_name is not None

    print(f"table={table}, metric={metric}, player={player_name}")

    generated_new_SQL = False

    # If extraction failed, skip cache and use old full-question LLM path
    if not table or not metric:
        sql = fallback_to_LLM(question) if use_fallback else None
        if not sql:
            return JsonResponse({
                "sql": None,
                "message": "Could not understand the question"
            })
    else:
        # Build cache key from extracted features
        key = json.dumps({"table": table, "metric": metric, "has_player": has_player}, sort_keys=True)

        sql = get_cache(key)

        if not sql:
            sql, generated_new_SQL = build_sql(table, metric, has_player, question)  # pass features, not raw question
            if generated_new_SQL:
                print('SQL generated by LLM: ')
            else : print ('SQL generated by template: ')
            print(sql)

    # Guardrails
    if sql == "please ask cricket related questions":
        return JsonResponse({"sql": None, "message": sql})

    if sql == "not in the data":
        if use_fallback:
            result = fallback_to_LLM(question)
            return JsonResponse({
                "sql": "No SQL generated",
                "result": result + "\n\nNOTE: This answer is not sourced from the database but from an external LLM"
            })
        return JsonResponse({"sql": None, "message": sql})

    # Safety check
    if not sql.strip().lower().startswith("select"):
        return JsonResponse({"sql": sql, "error": "Only SELECT queries are allowed"}, status=400)

    try:
        rows, columns = execute_SQL(sql, player_name)
        result = [span_to_JSON(columns, row) for row in rows]

        if not result:
            return JsonResponse({"sql": sql, "message": "No data found"})

        # Only cache if extraction succeeded, SQL is valid, and it was freshly generated
        if player_name and table and metric and redis_available and generated_new_SQL and sql not in INVALID_SQL:
            set_cache(key, sql)
            print(f"Cached: {key}")

        return JsonResponse({"sql": sql, "result": result})

    except Exception as e:
        return JsonResponse({"sql": sql, "error": str(e)}, status=500)